on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK:
        description: 'Webhook to projectname-dev slack channel'
        required: true
name: Send slack notification about action run
jobs:
  send-ended-notifications:
    name: Send slack notification
    runs-on: ubuntu-24.04
    steps:
      - name: Post a message in a Slack channel
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":checkered_flag: *GitHub Action* Finished: `${{ github.workflow }}` - ${{ job.status }}\n*Branch*: <https://github.com/${{ github.repository }}/tree/${{ github.ref_name }}|${{ github.ref_name }}>\n*Action Run*: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View in GitHub>"
                  }
                }
              ]
            }